### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by 5wi5wi** [ThatGuyJacobee/Elite-Music#75]
im hosting the bot on sparkedhost and im having this issue since the 1.5 update, i've tried to reinstall all the files and that didnt help.

the message: 

added 23 packages, and audited 253 packages in 2s
36 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
npm WARN config production Use `--omit=dev` instead.

up to date, audited 230 packages in 1s
33 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
[ELITE_ERROR] The .env file could not be found/doesn't exist. Have you followed the setup instructions correctly (https://github.com/ThatGuyJacobee/Elite-Music) to ensure that you have configured your environment correctly?

there is an ENV file and all the configurations are good.

**Comment by ThatGuyJacobee** [comment]
Hey, this is likely to do with the file structure or incorrect paths being set for the `.env` file. If you are hosting this on Windows or Linux, the `.env` file should be in the root folder, exactly where the original `.env.sample` was. 

However, if you are using Docker this might change things a little, as within the Docker command or Docker Compose `.yaml` file, you have to manually specify where the `.env` file will be located.

There is also the possibility that you simply forgot to copy and rename the `.env.sample` to simply `.env` for your true production-ready environment file.

**Comment by 5wi5wi** [comment]
yeah i did what you said and it works now
